---
name: Matrix Test

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - build-*

jobs:
  matrix-prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Set Matrix
        id: set-matrix
        run: |
          matrix=$( cat .github/workflows/base_node_binaries.json | jq -c . )
          echo $matrix
          echo $matrix | jq .
          echo "::set-output name=matrix::$matrix"

  matrix-check:
    runs-on: ubuntu-latest
    needs: matrix-prep
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix-prep.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml

  build:
    name: Build ${{ matrix.build }} on ${{ matrix.os }}
    needs: matrix-prep
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix-prep.outputs.matrix)}}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Echo
      run: echo "${{ matrix.build }}"
