---
name: Release Test

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - build-*

env:
  TBN_FILENAME: "leet_suite"

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
#    env:
      # Set to force version number, e.g., when no tag exists.
#      LEET_VERSION: TEST-0.0.4
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      leet_version: ${{ env.LEET_VERSION }}
    steps:
      - name: Get the release version from the tag
        shell: bash
        if: env.LEET_VERSION == ''
        run: |
          echo "LEET_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.LEET_VERSION }}"

      - name: Download builds and release notes
        uses: actions/download-artifact@v2
        with:
          path: builds

      - name: Create GitHub release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: release
        #uses: actions/create-release@v1
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.LEET_VERSION }}
          release_name: ${{ env.LEET_VERSION }}
          #body_path: ./builds/containerd-release-notes/release-notes.md
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          #prerelease: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

      - name: Upload release archive
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            builds/${{ env.TBN_FILENAME }}*
            LICENSE
            README.md
